function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Jan-2017 12:14:59

% Create figure
figure1 = figure('NumberTitle','off','Name','Time - Figure 1');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','GI Tract');
set(plot1(2),'DisplayName','Blood');
set(plot1(3),'DisplayName','Brain');

% Create xlabel
xlabel('Time (sec)');

% Create title
title('Concentration (molarity) vs. Time (sec)');

% Create ylabel
ylabel('Concentration (molarity)');

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northeastoutside','Interpreter','none');

